version: '3'

services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build: .
    environment:
      - MOSQUITTO_PASSWORDFILE=${MOSQUITTO_PASSWORDFILE}
    image: eclipse-mosquitto
    container_name: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
